const notes = [
  {
    date: "05/06/2024",
    title: "Cậu bạn mới",
    content: "Nay là ngày t lên đường đi Nhật. Hồi hộp vaiii. H t đang trên máy bay và tranh thủ viết một chút. Đây mới là lần thứ 2 t đi ra nước ngoài thôi.<br>Nói thật là t sợ không có bạn chơi cùng vl :))) nhưng chắc không sao lắm, ơn trời là sự hướng ngoại của t đã bật lên, không thì t tự kỉ mất. Cũng may là quen le vy với mai linh từ trước, chứ không thì thôi rồi, tại chúng nó quen mấy đứa khác cùng khối đi cùng đoàn mình, thế là t cũng dễ kết bạn mới hơn.<br>Trong mấy đứa đấy có thằng cu kì lạ vl :)))) ban đầu t nghĩ là nó nerd nerd cơ, tại cái kính chữ nhật trông kiểu trung bình mấy cu học tự nhiên. Nhưng mà khi nói chuyện với cậu bạn này… đá ae ạ :))) rất đá, xong lúc nói chuyện cứ nhảy nhảy, ném bóng.<br>Bro :))))) Weirdo vl.<br>Kì kì nhưng thú vị phết, chắc có thể chơi cùng trong suốt đợt đi Nhật này được.<br>(Dm t phải bỏ cái tư tưởng nuôi mập mờ ngay lập tức cũng được, không thì gặp thằng nào t cũng muốn dính dáng romantically với chúng nó thì chết.)<br>Dù sao thì mong đợt đi Nhật này thật vui agagagaggagh.",
    locked: false
  },
  {
    date: "10/06/2024",
    title: "A great journey",
    content: "Ngày cuối cùng t ở Nhật Bản roii. Chuyến đi này thật sự rất vui, rất rất vui ý. Và một người đã góp phần rất lớn vào sự thành công của chuyến đi này là cậu bạn kì lạ kia. Nói sao ta, t với b ý thật sự bonding rất tốt y.<br>Ngày đầu cậu ý dẫn cả đám đi ngắm sao ở chỗ nào đó siêu nhiều bậc thang, mặc dù chẳng sao lắm, nhưng vẫn rất vui. Đêm đó, t với cậu b cũng lần đầu tiên nhắn tin luôn :)))) còn là t nhắn trước, lại còn về bóng đá ạ. Xong rồi còn sơn móng tay nữa :)))) bựa. Cậu ấy còn ở trên phòng bọn con gái đến tận đêm, thật sự là không biết ngại a bro, còn nằm trên giường mlai nữa. Thật ra thì t thấy hơi ghen tị một xíu. I mean, t tưởng trong đám con gái n thân với t hơn cơ, hóa ra là không phải 😓. Nghe các bạn nói chuyện t còn thấy hơi lạc lõng, tại t như kiểu ở một thế giới khác với chúng nó ý, kiếp khối A. But nevermind:))) vẫn khá thú vị.<br>Ngày thứ 2 thì có mấy thứ loằng ngoằng hơn sảy ra. Thằng cu này uống cồn ae ạ. Cu cậu rủ mn uống cùng nhưng không ai đi cả, thế là cậu ấy ở đấy uống với mấy ac tình nguyện viên. Fr là rất weird. Lúc sau cậu ấy quay lại kí túc xá xong rủ mọi người xuống downtown cùng hai ac tình nguyện. Dm nma nhìn phát là biết hai ac đi date rồi, ngáo vl, hôm sau còn phải dậy sớm nữa mà đòi đi đến 2h sáng. Mãi t mới cản được xong đưa nó lên phòng. Nhờ sự trốn tập của t với cậu bạn mà kim anh nghi ngờ bọn t yêu nhau. Cdm mới quen 2 ngày thì yêu cái nỗi gì:))?? Đã thế cu cậu say xòn rồi còn tự nhận là mình thích b yến cùng đoàn:))))) Dm đáng lẽ ra t không nên nói cho bọn cgai ở đấy nma t hốt hoảng quá 😭 kiểu lần đầu thấy có người uống say xong nói linh tinh ý. So sorry bro. Ít nhất thì hôm sau mn cũng chill chill, không có gì khác lạ xảy ra cả. <br>Rồi mấy ngày tiếp theo ở nhà host, bọn t thật sự call siêu nhiều :)))) lạ vãi, ý là cũng chưa quen mấy mà nói chuyện như kiểu phải thân với nhau được mấy kiếp rồi. Đã thế còn sốc dếch như đúng rồi.Cậu này cũng thích tương tác vật lý cơ, cứ khoác vai, túm tay. T biết t thoải mái r nma bro lạ quá 😅 thích b yến mà thoải mái với t quá v. Cả đợt này t với cậu b cứ như dính với nhau ý, bạn thân sau vài ngày ạ.<br>Đêm qua bọn t rủ nhau làm tí Soju với nói chuyện. Cu cậu uống tí mà mặt đỏ như tôm luộc, nhìn là biết say rồi. Thế là t đưa cậu về phòng. Thế nào t với cậu b lại nói chuyện đến 3h sáng luôn. T ngồi trên ghế, cậu b nằm trên giường. Hơi đau lưng, mỏi cổ nhưng mà i know giới hạn, t chừa vl r. Nói hoài, nói mãi t mới về phòng đi ngủ.<br> Cậu bạn này phải chiếm hết một nửa thời lượng chuyến du lịch này của t, nhưng chắc tình bạn này cũng chẳng bền lắm đâu nhỉ.<br><br>",
    locked: false
  },
  {
    date: "12/06/2024",
    title: "Một tối",
    content: "Nay lại là một ngày kì lạ :)))<br> T và cậu ấy đi lượn quanh Hồ Tây, gió thổi mát lạnh, mang theo mùi nước hồ và một chút hương cá (thật sự hơi tanh).<br>Chỉ mới quen nhau hơn một tuần, mà lần đầu tiên t thấy nói chuyện với ai lại thoải mái đến vậy. Cậu ấy lắm mồm, t cũng lắm mồm, hai đứa nói đủ loại chuyện, từ bình thường đến shock vl, nhưng lại vừa vặn và vui khôn tả. Thật ra t cũng không nhớ rõ đã nói gì, chỉ biết là cực kì vui :))))<br>Sau một lúc đi dạo, cậu ấy dẫn t ra bãi cỏ ven hồ. Hồ Tây về đêm đẹp mê hồn: ánh sáng từ các tòa nhà phản chiếu trên mặt nước lấp lánh, lung linh như dải sao mắc kẹt giữa đất và trời.<br>Cậu ấy đứng im một lúc, nhìn t rồi khen: “Mặc đồ hôm nay đẹp thật đấy.” Ừ thì t mà nhưng vui vl, lâu lắm mới có người khen mặc đẹp. <br>Hai đứa ngồi xuống trên ghế dài, bật Hà Nội, tận hưởng không khí ấy. Xung quanh chỉ còn cây, cỏ và gió, như mọi muộn phiền đều biến mất, t chỉ còn là t. <br> Rồi cậu ấy bất ngờ bảo: “Cho t nằm đùi nhé?” T đứng hình một giây, nhưng ngại từ chối, nên đồng ý.<br>Cậu ấy chỉ nằm đó thôi, thỉnh thoảng lảm nhảm về crush, vừa phiền vừa buồn cười.<br>Cảm giác kì quặc nhưng cũng thú vị.<br>Ngắm ánh sáng phản chiếu trên hồ, nghe nhạc, cười linh tinh, t nhận ra một điều:“Chắc mình sẽ nhớ hôm nay lâu lắm.”<br>Chỉ cần có cậu ấy, thế giới bỗng bị bỏ lại đằng sau. <br> T được cười thoải mái, được nghĩ linh tinh, và được quên đi thực tại.",
    locked: false
  },
  {
    date: "16/07/2024",
    title: "On his birthday",
    content: "Hôm qua là sinh nhật cậu bạn ấy nma nay t, cậu ấy và mlai rủ nhau đi chơi chung.<br>Ban đầu cái bánh t định làm cho cậu ấy sẽ là kiểu panna cotta phiên bản to hơn ý. Nhưng mà fail quá dm nên t phải rush làm gấp một cái bánh khác vị chanh leo. Ommm, t thề là bánh khá vị trứng vì hnhu t làm rớt một ít lòng đỏ vào lòng trắng nên hơi khó đánh bông, cộng thêm quên vani. Dm fail x2. Ngặt nỗi là lúc đấy muộn rồi nên đành chịu 🥹<br>Xong còn đen nữa là quán cafe bọn t định đi còn đóng cửa. Dm ý là t không biết tại sao cậu ý có thể đen đến thế vào sinh nhật của mình ý.<br>Well, bọn t đành đi ăn chè, khá tạm bợ nhưng ít nhất thì chè ngon. Cậu ý còn khen bánh t làm. Nói thật thì t không tự tin với cái bánh đấy lắm dm, nhưng mà yeh, rất appreciate.<br>Ít nhất thì t có tặng cậu ấy cái thiệp rất tử tế.<br>Ăn chè xong cả đám sang nhà cậu ấy ăn ạ :)))) thôi may mà còn được ăn.<br>Yeyy, snhat vui vẻ cậu bạn của t. ",
    locked: false
  },
  {
    date: "21/09/2024",
    title: "Ngày kia sinh nhật",
    content: "T với cậu ấy cãi nhau 😀. <br>Không hẳn là cãi nhau, chỉ là t muốn tránh mặt thôi.<br>Cậu ấy muốn bọn t giữ khoảng cách vì cậu ấy thích bạn yến quá :))) muốn có cơ hội.<br> Bruh, muốn giữ khoảng cách mà hôm nói cái đấy lại đòi ôm t, kì vl :)??<br>Ý là t fine thôi, chỉ là hơi khó chịu, nhiều chút. Cảm giác kiểu tình bạn của bọn t cũng khá gắn bó rồi, xong cậu ấy lại nói là muốn tránh nhau ra tí. Không khó chịu cũng khó. T gặp cũng không muốn chào lắm.<br>Thôi chắc tb tình bạn :))) khó bền phết, cũng không phải một lần nữa rồi.<br>Chả hiểu sao cứ “Biết đâu ở vũ trụ khác t với m lại yêu nhau bla bla bla” xong giờ lại “T muốn giữ khoảng cách vì yến”. Ok thôi.<br>À nay t mới ra mê và viết vào một quyển sổ ở đấy. Giống tâm sự hơn, tâm sự về chuyện này. Vì t cảm thấy năm nào sinh nhật t cũng có chuyện, và lần này thì là chuyện của t với cậu ấy.<br>Hài thật.",
    locked: false
  },
  {
    date: "08/11/2024",
    title: "VAI CUT",
    content: "Hôm nay cậu ấy tỏ tình t ae ạ 😰<br>Sốc vcc<br> Cậu ấy bảo trong lúc đang nằm trên giường chuẩn bị ngủ trưa khi đang làm nghiên cứu khoa học ở nhà cậu ấy.<br>Dm thật ra ban đầu t không định nằm với cậu ấy lắm, nam nữ thụ thụ bất thân mà, nhưng mà mệt quá nên đành vậy.<br>Chỉ là không ngờ đặt lưng xuống cái cậu ấy lại nói “M có muốn thử tìm hiểu không.<br>Kiểu Ê VÃI Ý. T sốc vcl.<br>Đáng lẽ ra t nên cầm đồ về luôn và bảo “Cho t 3 ngày để suy nghĩ”. Nhưng t đã đ làm thế. T nhắn tin hỏi mtue, nma n đ rep lúc đấy cdm. Thế là t phải tự quyết. I mean đang nằm trên cùng 1 cái giường mà không trả lời luôn thì cũng kì.<br>Nên t đồng ý ae ạ 😅<br>Chắc là thử cũng được, không sao đâu nhỉ…<br>T trả lời xong cậu ý thơm t siêu nhiều, kiểu ở khắp mặt ý. Xong ôm nhau đi ngủ:)))<br>Giờ vẫn sốc vl…",
    locked: false
  },
  {
    date: "29/03/2025",
    title: "I'm moved",
    content: "Sau thời gian tìm hiểu dài vcl thì hôm nay cậu ý ngỏ lời yêu nhau chính thức rồi T.T<br>Mặc dù t không tỏ ra gì lắm nhưng mà xúc động quá ae 😭<br>Hôm qua là sự kiện chính engfes, và cậu ấy qua đêm ở nhà t :))) ncl cũng nhiều thứ xảy ra và điên loạn phết.<br>Nhưng mà thứ duy nhất t quan tâm là cậu ấy không quên lời hứa của mình. Mặc dù thật ra t đã cho rằng bọn t được tính là yêu nhau từ tháng 11 năm ngoái rồi.<br>Dù sao thì yehhh, t chính thức có ny rồi ae.<br>Hope that everything will go well in the future.",
    locked: false,
  },
  {
    date: "15/05/2025",
    title: "Đến lạ",
	content:"T với cậu ấy không nói chuyện một tuần rồi.<br>Mọi thứ đã không ổn từ trước rồi. Bằng một cách nào đó t đã thấy vô cùng khó chịu với cậu ấy. Chắc là do cậu ấy đã nói chuyện “nhạy cảm” với Phan Khánh Linh mà không nói cho t.<br>Ý là nó không nên bị đẩy đến mức độ cao trào đến thế, chỉ là t không hiểu sao nhưng t rất khó chịu ý, không chịu nổi. Một phần có lẽ là do sự lạnh nhạt của cậu ấy khi mới về nước.<br>Trước khi cậu ấy bay, t đã bảo với mtue về sự lo lắng của t, về việc t sợ rằng khi đi xa như thế cậu ý sẽ quên mất t và thích người khác.<br>Dme đ ngờ đúng thật. Cay vcc.<br>Ccho này thích người khác xong giấu t, nhưng mà lại kể cho Phan Khánh Linh. Riết không biết nói sao.<br>Ngày mai bọn t sẽ đi nói chuyện về việc này. T đã tham khảo ý kiến của rất nhiều người, viết một đoạn dài 3000 từ để nói chuyện thật nghiêm túc.<br>Chẳng biết có đi xa được tiếp không, nhưng dù là như thế nào t cũng chấp nhận.",
    locked: false,
  },
  {
    date: "15/07/2025",
    title: "Another birthday",
	content:"Hôm nay đúng sinh nhật của cậu ấy luôn. Yeyyy. Năm ngoái không đúng ngày nhưng năm nay thì đúng rồi. <br> Năm nay t làm cho cậu ấy hoành tráng luôn. Bánh sinh nhật to to, tiramisu và trà sữa.<br>T còn thức xuyên đêm, thật sự không ngủ tí nào, để làm bánh sinh nhật cho cậu ấy.<br>NHƯNG MÀ bánh bị đổ 😭<br>T thật sự rất buồn ý, công sức cả đem của t huhuuhuuhu.<br>Nhưng mà cậu ấy bảo cậu ấy thích lắm 🥹 Đỡ buồn hơn một chút..<br> Dù sao thì t vẫn ước mình đã chụp ảnh cái bánh đấy lại..<br>Oh, và năm nay bọn t sang nhà cậu ấy để đánh úp, t với mlai:))))<br>Ban đầu đi xòn suýt lạc vì t bị đơ, thiếu ngủ quá.<br>Mặc dù hơi vấn đề một chút, và t đơ nhiều chút nhưng vẫn rất vui.<br>Happy birthday bro.",
    locked: false,
  },
  {
    date: "22/11/2025",
    title: "Done",
	content:"Ồ.<br>Hôm nay t và cậu ấy chia tay.<br>Đáng lẽ ra cũng không nên bị đẩy lên đến mức đấy, nhưng t không thể handle việc cậu ấy muốn bỏ t. Nên t mới nóng giận mà quyết chia tay luôn.<br>T cũng viết rất nhiều trên insta rồi nên t chẳng muốn nói gì nữa.<br>Chắc hôm nay đến đây thôi.<br> Cuối cùng t vẫn luôn là người ở lại.",
    locked: false,
  },
  {
    date: "27/11/2025",
    title: "Ê ý",
	content:"Dme. Thằng này.<br>Chia tay xong đi chơi với con khác luôn, thế mà cứ luôn mồm bảo t muốn quan tâm m này nọ kia ấy đó.<br>Lại còn là yến phạm.<br>gg<br>Đã thế nó còn bảo là trong lúc yêu t nó còn thích yến phạm lại. TRONG MỘT TUẦN. VCC ạ.<br> Ê ý. Ý là sao vậy bro.<br>T bị cáu ý. T ghét nó vl.<br>Biết là sai mà sao vẫn làm :))) logic khó hiểu vl.<br>Chả hiểu còn yêu ở đâu.<br>Chắc là do t chưa đủ tốt, làm bạn cô đơn quá nên thích tận 2 người trong lúc còn yêu t.<br>Xin lỗi.",
    locked: false,
  },
  {
    date: "14/12/2025",
    title: "Nay kỉ",
	content:"Nay t kỉ yếu.<br>Cậu ý xuất hiện từ sáng sớm luôn :)))) không biết để làm gì ạ<br>Cậu ý cứ lượn lờ quanh t tí xong đưa t bánh đậu xanh, xong đi về.<br>Lúc sau đến giờ chụp người thân bạn bè thì lại đến lại với cái bạt (tại vì t bảo t thích bạt :)))))<br>Đến xong còn ngại ngại bạn t. Buồn cười phết :)))) Xong rồi cậu ấy lại làm culi cho t cả sáng, rồi còn giúp t tải ảnh về vì máy t cứ sập nữa.<br>Yeh nhưng mà t với bạn ý nói chuyện xong chơi lại được khá lâu rồi. Và chơi nhau lại khá lâu rồi.<br>Cũng kì lạ phết khi mà cứ gọi nhau là bạn thân xong rồi làm mấy cái freaky ah.<br>But everything is still great, at least i think so. ",
    locked: false,
  },
  {
  date: "25/12/2025",
  title: "Một bức thư",
  locked: true,
  password: "camonvidaden",
  content: `
  <p>"Gửi cậu, người đã gắn bó với t suốt thời gian vừa qua. <br> Nói sao nhỉ t với m cũng đã đi một chặng đường khá là dài rồi. Và t không thể phủ nhận sự gắn bó của chúng mình.<br>T vẫn còn nhớ những ngày rong ruổi trên con xe màu xanh, những ngày đi chơi dài suốt cả ngày, những buổi nói chuyện đêm, những lúc t với m cứ thoải mái mà nói chuyện. Đó là câu chuyện của mùa hè năm ấy, một mùa hè tuổi 16 rất đẹp, rất tuyệt vời, mà nếu không có m chắc mùa hè ấy của t cũng chỉ là một mùa hè bình thường như bao mùa hè khác.<br>T chưa bao giờ hối hận vì đã gặp m, nếu có hối hận thì sẽ là hối hận vì những khi t chưa suy nghĩ kĩ mà đã hành động, khiến cho cả hai đứa bị ảnh hưởng thôi.<br>T chưa từng nghĩ câu chuyện của mùa hè ấy lại kéo dài đến vậy, lại tiến triển xa đến thế, khi nó còn kéo đến tận năm lớp 12 và tiến đến một mối quan hệ nghiêm túc. Và t cũng không thể ngờ t với m còn yêu nhau tận 1 năm. Đấy đã từng là một khoảng thời gian không tưởng với t, nhất là khi t đã vô tình đánh mất sự tin tưởng vào bất kì mối quan hệ xã hội nào.<br>T sẽ không nói thêm về sự buồn bã, trách móc hay cãi vã gì ở đây cả. T sẽ chỉ nói về việc m đã để lại cho t những gì. M để lại cho t niềm tin. Mặc dù t từng nói là m xây nó lại và lại đập nó đi, nhưng giờ nghĩ lại, điều đó cũng không đúng. M chưa từng đập nó đi, nó vẫn ở đấy, kiên cố như ngày nào. M đã giúp t dần có sự tự tin trong các mối quan hệ, và từ đó có thể phát triển các mối quan hệ bạn bè của t.<br>M biết không t rất ngưỡng mộ sự hoạt ngôn và vô tư trong việc nói chuyện của m. M có thể dễ dàng bắt chuyện với người khác một cách rất tự nhiên mà không ngại, kể cả khi đó là cụ bà 80 hay cô bé 8 tuổi. Đấy thực sự là một loại tài năng, một loại kĩ năng mà t không học được.<br>Và m luôn muốn học hỏi. T không biết m có nhìn ra không, t mong là có, nhưng t thấy được sự muốn thay đổi để tốt hơn của m. Từ rất lâu rồi. Mặc dù giai đoạn yêu đương với t m có hơi bỏ qua bản thân một nhiều chút, nhưng m đã cố gắng trong việc học tập, rất tiến bộ luôn. Và giờ thì m còn học cả nấu ăn nữa. Khá là tuyệt vời. M còn đặc biệt giỏi trong việc tìm kiếm thông tin, và hỏi về các thông tin nữa. I mean, t khá tệ khoản đấy :)))) t còn không biết t muốn hỏi gì cơ.<br>M còn rất là quan tâm nữa. M cứ nghĩ rằng mình vô cảm thôi, giống như t nghĩ m ích kỷ vậy. Nhưng m luôn quan tâm đến Diệp, đến mẹ, đến cả t nữa. Idk có thể là không luôn lắm, nhưng mà ít nhất là có. Nên nó chứng minh là m không hề vô tâm, m rất có tâm.<br>Dù sao thì, cũng gần hết năm rồi, và bức thư này là để chúc mừng giáng sinh nên là:.<br>MỪNG GIÁNG SINH AN LÀNH!!<br>Mong rằng quà giáng sinh của m sẽ là đạt được aims của bản thân, vào được trường m yêu thích, không bị bố mẹ mắng nhiều nữa, khỏe mạnh, cẩn thân hơn không để mình bị thương, thi lần nào cũng trên 36 điểm và sớm gặp được người yêu thương m thật nhiều.<br>Cảm ơn vì đã đến bên t.<br>P/S: Hãy giải puzzle và đi tìm kho báu!!<br><br><p>
  <a href="puzzle.html" target="_blank">
     Truy tìm kho báu
  </a>
  <div class="locked-box" data-password="tyeum">
    <div class="locked-header">🔒 Secret box</div>
    <input type="password" placeholder="Enter password" />
    <button onclick="unlockBox(this)">Unlock</button>
    <div class="locked-content">
      <p>M ơi, thật ra t vẫn còn yêu m nhiều lắm. Chắc m cũng nhận ra rùi.<br>Chỉ là t muốn m có thể đạt được những điều m đang hướng tới, và t không muốn cản bước m thoi.<br>Và đôi khi t vẫn cảm thấy hơi chạnh long chút chút :))))<br> (Chắc là trong một mqh thì ai cũng nghĩ mình là người yêu nhiều hơn nên sẽ expect nhiều hơn từ người mình yêu.)<br>Dù sao thì t không biết m sẽ ở cạnh t đến khi nào, nhưng mà t biết m thực sự đã làm t rất vui, và t trân trọng những cố gắng của m. T biết m yêu t nhiều, và những lúc m làm t buồn chỉ là m thiếu suy nghĩ thoi. Nhưng mà t không muốn bị buồn :(<br>Hì, dù sao thì hôm nay t đã viết ra điều mà t muốn nói rùi. Đó là t yêu m nhiều lắm, chỉ là t sợ đây chưa phải là lúc thích hợp để nói ra mà thôi (và t sợ bị tổn thương nua).<br>P/S x2: T sẽ siêu trông chờ vào biểu hiện của m để xem t có nên chấp nhận việc làm ny m x2 không đấy 😛.</p>
    </div>
   </div>
  `
},

];
